"""empty message

Revision ID: e3342c341d1d
Revises: 0abc32aa5db0
Create Date: 2025-03-22 17:32:09.499804

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e3342c341d1d"
down_revision: Union[str, None] = "0abc32aa5db0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
